@startuml casoUso
actor Administrador
actor "Personal de Museo" as Personal

rectangle "Sistema del Museo" {
    Personal --> (Consultar piezas)
    Personal --> (Realizar préstamo de pieza)
    Personal --> (Devolver pieza)
    Personal --> (Registrar pieza)
    Personal --> (Consultar piezas)
    Personal --> (Realizar préstamo de pieza)
    Personal --> (Devolver pieza)
    Personal --> (Consultar estado de pieza)
    Personal --> (Generar reportes de inventario)
    Personal --> (Registrar proceso de taxidermia)
    Administrador --> (Administrar usuarios)
}
@enduml
