@startuml diagramaDeClases

class Pieza {
    -NumeroRegistro : String
    -NombrePieza : String
    -MedidaPieza : String
    -MaterialObjeto : String
    -FechaAdquisicion : Date
    -FormaAdquirida : String
    -AñoPieza : Integer
    -EstadoPieza : String
    -Cantidad : Integer
    -Observacion : String
    -BajaLogica : Boolean
    -class : String
    +Pieza(nroR, nomP, medidaP, materialOb, fechaAd, formaAdq, añoPi, estadoPi, cantidad, Obse, supr)
    +fromJSON(json) : Pieza
}

class Prestamo {
    -numeroPrestamo : Integer
    -numeroPiezas : Integer
    -eventoPrestamo : String
    -fechaPrestamo : Date
    -fechaDevolucion : Date
    -cantidad : Integer
    -observacionPrestamo : String
    -class : String
    +Prestamo(numPres, numPieza, eventoPre, fechaPre, fechaDev, cant, obsePre)
    +fromJSON(json) : Prestamo
}

class Prestamoestado {
    -idPrestamoEstado : Integer
    -bandera : Boolean
    -estadoPieza : String
    -class : String
    +Prestamoestado(idPrEs, band, estadoPi)
    +fromJSON(json) : Prestamoestado
}

class Taxidermia {
    -idTaxidermia : Integer
    -fechaMantenimiento : Date
    -observacionTaxidermia : String
    -idPieza : Integer
    -class : String
    +Taxidermia(idTax, fechaM, obseTax, idPieza)
    +fromJSON(json) : Taxidermia
}

class Piezaestado {
    -idPiezaEstado : Integer
    -bandera : Boolean
    -class : String
    +Piezaestado(idPEs, ban)
    +fromJSON(json) : Piezaestado
}

class EstadiPieza {
    -idEstadoPieza : Integer
    -fechaEstado : Date
    -idPieza : Integer
    -idPiezaEstado : Integer
    -class : String
    +EstadiPieza(idEP, fechaEP, idPieza, idPE)
    +fromJSON(json) : EstadiPieza
}

class Usuario {
    -nombre : String
    -usuario : String
    -pass : String
    -token : String
    -class : String
    +Usuario(nombre, usuario, pass, token)
    +fromJSON(json) : Usuario
}

Pieza "1" -- "*" Prestamo : "contiene"
Pieza "1" -- "*" Prestamoestado : "tiene"
Pieza "1" -- "*" Taxidermia : "es sujeto de"
Pieza "1" -- "*" EstadiPieza : "cambia estado"
EstadiPieza "1" -- "1" Piezaestado : "tiene"
Prestamo "1" -- "*" Prestamoestado : "cambia estado"

@enduml