@startuml
actor Usuario
participant "Controlador" as Controlador
participant "Modelo" as Modelo
participant "Base de Datos" as DB

Usuario -> Controlador: registrarPrestamo(data) // Registro
Controlador -> Modelo: guardarPrestamo(nuevoPrestamo)
Modelo -> DB: write prestamos.txt
DB --> Modelo: confirmación
Controlador --> Usuario: { exito: true, mensaje: "Préstamo registrado con éxito" }

Usuario -> Controlador: modificarPrestamo(prestamoMod) // Modificación
Controlador -> Modelo: actualizarPrestamo(prestamoMod)
Modelo -> DB: write prestamos.txt
DB --> Modelo: confirmación
Controlador --> Usuario: { exito: true, mensaje: "Préstamo modificado con éxito" }

Usuario -> Controlador: eliminarPrestamo(numeroRegistro) // Eliminación
Controlador -> Modelo: eliminarPrestamo(numeroRegistro)
Modelo -> DB: write prestamos.txt
DB --> Modelo: confirmación
Controlador --> Usuario: { exito: true, mensaje: "Préstamo eliminado con éxito" }
@enduml