@startuml secuenciaTaxidermia
actor Usuario
participant "Controlador" as Controlador
participant "Modelo" as Modelo
participant "Base de Datos" as DB

Usuario -> Controlador: registrarPieza(data) // Registro
Controlador -> Modelo: guardarPieza(nuevaPieza)
Modelo -> DB: write db.txt
DB --> Modelo: confirmación
Controlador --> Usuario: { exito: true, mensaje: "Pieza de taxidermia registrada con éxito" }

Usuario -> Controlador: modificarPieza(piezaMod) // Modificación
Controlador -> Modelo: actualizarPieza(piezaMod)
Modelo -> DB: write db.txt
DB --> Modelo: confirmación
Controlador --> Usuario: { exito: true, mensaje: "Pieza de taxidermia actualizada con éxito" }

Usuario -> Controlador: eliminarPieza(numeroRegistro) // Eliminación
Controlador -> Modelo: actualizarBajaLogica(numeroRegistro)
Modelo -> DB: write db.txt
DB --> Modelo: confirmación
Controlador --> Usuario: { exito: true, mensaje: "Pieza de taxidermia eliminada lógicamente" }
@enduml